name: Test Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          # - mips_24kc

    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Bild SDK test
        run: |
          docker run -v ${{ GITHUB.WORKSPACE }}:/builder/package/feeds/ci openwrt/sdk:${{ matrix.arch }}-v23.05.5 sh -c "
          ./scripts/feeds update -a
          make package/podkop/{ clean, compile } V=s
          ls bin/packages/x86_64/ci
          "

      # - name: Store packages
      #   uses: actions/upload-artifact@v4.4.3
      #   with:
      #     name: ${{ matrix.arch}}-packages
      #     path: bin/packages/${{ matrix.arch }}/packages/*.ipk